services:
  homeassistant:
    container_name: homeassistant-myfund-testing
    image: homeassistant/home-assistant:stable
    volumes:
      - ha-config:/config
      - ./testing/configuration.yaml:/config/configuration.yaml
      - ./custom_components/myfund:/config/custom_components/myfund
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

volumes:
  ha-config: